---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, astra trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config 
summary: 您必須先在主機上安裝並設定必要的傳輸協定先決條件、才能部署Astra Trident。 
---
= 部署的先決條件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


您必須先在主機上安裝並設定必要的傳輸協定先決條件、才能部署Astra Trident。

* 確認您的部署符合所有的 link:../trident-get-started/requirements.html["需求"^]。
* 確認您安裝的Docker版本受支援。如果您的Docker版本過時、 https://docs.docker.com/engine/install/["安裝或更新"^]。


[listing]
----
docker --version
----
* 確認已在您的主機上安裝及設定通訊協定先決條件：


[cols="3*"]
|===
| 傳輸協定 | 作業系統 | 命令 


| NFS  a| 
RHEL/CentOS 7.
 a| 
`sudo yum install -y nfs-utils`



| NFS  a| 
Ubuntu
 a| 
`sudo apt-get install -y nfs-common`



| iSCSI  a| 
RHEL/CentOS 7.
 a| 
. 安裝下列系統套件：
+
`sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath`

. 啟動多重路徑精靈：
+
`sudo mpathconf --enable --with_multipathd y`

. 請確保如此 `iscsid` 和 `multipathd` 已啟用並執行：
+
`sudo systemctl enable iscsid multipathd`
`sudo systemctl start iscsid multipathd`

. 探索iSCSI目標：
+
`sudo iscsiadm -m discoverydb -t st -p <DATA_LIF_IP> --discover`

. 登入探索到的iSCSI目標：
+
`sudo iscsiadm -m node -p <DATA_LIF_IP> --login`

. 啟用並啟動 `iscsi`：
+
`sudo systemctl enable iscsi`
`sudo systemctl start iscsi`





| iSCSI  a| 
Ubuntu
 a| 
. 安裝下列系統套件：
+
`sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools`

. 啟用多重路徑：
+
`sudo tee /etc/multipath.conf <<-'EOF'
defaults {
    user_friendly_names yes
    find_multipaths yes
}
EOF
sudo service multipath-tools restart`

. 請確保如此 `iscsid` 和 `multipathd` 執行中：
+
`sudo service open-iscsi start
sudo service multipath-tools start`

. 探索iSCSI目標：
+
`sudo iscsiadm -m discoverydb -t st -p <DATA_LIF_IP> --discover`

. 登入探索到的iSCSI目標：
+
`sudo iscsiadm -m node -p <DATA_LIF_IP> --login`



|===